### ISSUE TITLE
react-native-pedometer: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by markmarincek** [galmis/react-native-pedometer#5]
When I add libRNPedometer.a to the Link Binary With Libraries my application wont't build successfully and I will get error: linker command failed with exit code 1 (use -v to see invocation).
I followed installation instructions down to the letter so now I am kind of lost. Any help would be much appreciated.

<img width="850" alt="screen shot 2017-12-22 at 17 39 21" src="https://user-images.githubusercontent.com/26083816/34305701-9fa7b0ac-e73f-11e7-8a70-e78bfbd93691.png">

**Comment by swiftdesignjp** [comment]
Does React.xcodeproj exist in RNPedometer.xcodeproj of Libraries? I deleted that React.xcodeproj and it was built successfully.

**Comment by markmarincek** [comment]
That solved the issue. Thank you.
